### ISSUE TITLE
New Mac OS X, New Google Hash Errors

### ISSUE THREAD

**Issue by billywatson** [rdp/google_hash#38]
Hello again,

You've been very helpful in the past on "google hash not building on the newest OS X" errors so I appreciate any help you can provide here.

I've captured the log output in a gist 
https://gist.github.com/billywatson/6d75f07c6954b7274034

My gcc is: 

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

I'm using Mac OS X El Capitan 10.11 and XCode 7.0.1

**Comment by rdp** [comment]
appears to be this
https://github.com/sparsehash/sparsehash/issues/111
should we wait for them to fix it or do you need it asap?

**Comment by rdp** [comment]
try the latest version, I tried a hint that homebrew was using

**Comment by billywatson** [comment]
No super rush. I've got teammates that can run certain tests for me, if the need arises. 

Wow, thanks for the quick fix! I'll give it a shot.

**Comment by billywatson** [comment]
That install worked. Your magic and fairy dust works well, as always. Thanks!

**Comment by rdp** [comment]
good thing the homebrew people had run into this and identified the right
fix already LOL

**Comment by vnazarenko** [comment]
Hey, I've build problems also ... 
tr1/functional is missing ...
Could you suggest how to fix that ?

**Comment by rdp** [comment]
using the latest? what OS?

**Comment by vnazarenko** [comment]
Mac ElCapitan 10.11.6
` $  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1 
 
Apple LLVM version 7.3.0 ( clang-703.0.31)
 Target: x86_64-apple-darwin15.6.0 
 Thread model: posix`
Output: https://gist.github.com/vnazarenko/fcea922a853700b54625af2714e0897f
mkmf log: https://gist.github.com/vnazarenko/db4e48d5464a62eb66a3e7d79b9040e2

**Comment by rdp** [comment]
OK I got the same failure with ruby 2.3.0 but seemed to work with 2.3.1 ?
same there?
